# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/WuHuHu-666/android_kernel_xiaomi_msm8996
          kernel-dir: msm-4.4
          kernel-branch: lineage-21
          config: msm-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          android-version: 14
          aosp-clang-version: r4877747c
          disable-lto: true
          anykernel3: true
